language: r
sudo: required
dist: trusty
cache: packages

## Set up the matrix of different runs
env:
  matrix:
  - r: release
    not_cran: true
    r_check_args: "--no-manual"
  - r: release
    not_cran: false
    r_check_args: "--no-manual --as--cran"

before_install:
- sudo apt-get install -y libgdal-dev libproj-dev

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
